xCloud.Task7/Models/ErrorViewModel.cs
namespace xCloud.Task7.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

xCloud.Task7/Models/ImageMetadataModel.cs
using System;

namespace xCloud.Task7.Models
{
    public class ImageMetadataModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime UpdatedOn { get; set; }

        public long SizeInBytes { get; set; }

        public string FileExtension { get; set; }
    }
}

xCloud.Task7/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using xCloud.Task7.Models;

namespace xCloud.Task7.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

xCloud.Task7/Controllers/ImagesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using xCloud.Task7.Interfaces;

namespace xCloud.Task7.Controllers
{
    public class ImagesController : Controller
    {
        private readonly IImageService _imageService;
        private readonly IS3Service _s3Service;
        private readonly ISqsService _sqsService;

        public ImagesController(IImageService imageService, IS3Service S3Service, ISqsService sqsService)
        {
            _imageService = imageService;
            _s3Service = S3Service;
            _sqsService = sqsService;
        }

        [HttpGet]
        public IActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            var image = await _s3Service.UploadFileToS3BucketAsync(file);

            await _imageService.AddMetadataToDatabaseAsync(image);
            
            var message = @$"Image with name {image.Name}, extension {image.FileExtension} 
                            and size {image.SizeInBytes} was uploaded! 
                            You can download it here: {Request.Path.Value}";
            
            await _sqsService.PublishEventToSqsQueue(message);

            return RedirectToAction("AllFiles");
        }

        public async Task<IActionResult> AllFiles()
        {
            return View(await _imageService.GetImagesMetadataAsync());
        }

        public async Task<IActionResult> DownloadFileAsync(int id)
        {
            var image = await _imageService.GetImageMetadataByIdAsync(id);
            var bucketObjectResponse = await _s3Service.DownloadFileAsync(image);

            if (image is null)
            {
                return NotFound();
            }

            return File(bucketObjectResponse.ResponseStream, bucketObjectResponse.Headers.ContentType,
                bucketObjectResponse.Key);
        }

        public async Task<IActionResult> DeleteFile(int id)
        {
            var imageName = await _imageService.DeleteMetadataByIdAsync(id);

            await _s3Service.DeleteFileAsync(imageName);
            
            return RedirectToAction("AllFiles");
        }
    }
}

xCloud.Task7/Controllers/LambdaController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using xCloud.Task7.Interfaces;

namespace xCloud.Task7.Controllers
{
    public class LambdaController : Controller
    {
        private IAwsService _awsService;

        public LambdaController(IAwsService awsService)
        {
            _awsService = awsService;
        }

        [HttpGet]
        public IActionResult TriggerLambda()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> TriggerLambda(string payload)
        {
            await _awsService.InvokeLambda(payload);

            return View();
        }
    }
}

xCloud.Task7/Controllers/SubscriptionController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using xCloud.Task7.Interfaces;

namespace xCloud.Task7.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly ISubscriptionService _subscriptionService;

        public SubscriptionController(ISubscriptionService subscriptionService)
        {
            _subscriptionService = subscriptionService;
        }

        [HttpGet]
        public IActionResult SubscribeForNotifications()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> SubscribeForNotifications(string email)
        {
            var subscribeResponse = await _subscriptionService.SubscribeForNotifications(email);

            if (subscribeResponse is null)
            {
                return NotFound();
            }
            
            return View(subscribeResponse.ResponseMetadata);
        }
        
        [HttpGet]
        public IActionResult UnsubscribeFromTopic()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> UnsubscribeFromTopic(string email)
        {
            var unsubscribeResponse = await _subscriptionService.UnsubscribeFromTopic(email);

            if (unsubscribeResponse is null)
            {
                return NotFound();
            }
            
            return View(unsubscribeResponse.ResponseMetadata);
        }
    }
}

xCloud.Task7/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

xCloud.Task7/Views/Images/AllFiles.cshtml
@model List<ImageMetadataModel>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>FileExtension</th>
        <th>SizeInBytes</th>
        <th>UpdatedOn</th>
        <th>Download</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>

    @foreach (var image in Model)
    {
        <tr>
            <td>@image.Id</td>
            <td>@image.Name</td>
            <td>@image.FileExtension</td>
            <td>@image.SizeInBytes</td>
            <td>@image.UpdatedOn</td>
            <td>
                <a class="btn btn-success" href="/Images/DownloadFileAsync/@image.Id">Download</a>
            </td>
            <td>
                <a class="btn btn-danger" href="/Images/DeleteFile/@image.Id">Delete</a>
            </td>
        </tr>
    }
    
    </tbody>
</table>

xCloud.Task7/Views/Images/UploadFile.cshtml
<form asp-controller="Images" asp-action="UploadFile" enctype="multipart/form-data" method="post">
    <dl>
        <dt>
            <label>Upload</label>
        </dt>
        <dd>
            <input name="file" id="file" type="file">
        </dd>
    </dl>
    <input class="btn btn-success" type="submit" value="Upload">
</form>

xCloud.Task7/Views/Lambda/TriggerLambda.cshtml
<form asp-controller="Lambda" asp-action="TriggerLambda" method="post">
    <div class="form-group">
        <label for="payload">Enter payload here:</label>
        <input type="text" name="uri" class="form-control" id="payload" aria-describedby="payload" placeholder="Enter payload">
        <small class="form-text text-muted">GIVE ME THE PAYLOAD!!!</small>
    </div>
    <button type="submit" class="btn btn-primary" value="payload">SEND</button>
</form>

xCloud.Task7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - xCloud.Task7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xCloud.Task7</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="AllFiles">Images</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="UploadFile">Upload an image</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="SubscribeForNotifications">Subscribe</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="UnsubscribeFromTopic">Unsubscribe</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Lambda" asp-action="TriggerLambda">Trigger lambda</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - xCloud.Task7 - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xCloud.Task7/Views/Subscription/SubscribeForNotifications.cshtml
<form asp-controller="Subscription" asp-action="SubscribeForNotifications" method="post">
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <button type="submit" class="btn btn-primary" value="email">Subscribe</button>
</form>

xCloud.Task7/Views/Subscription/UnsubscribeFromTopic.cshtml
<form asp-controller="Subscription" asp-action="UnsubscribeFromTopic" method="post">
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">Bye!</small>
    </div>
    <button type="submit" class="btn btn-primary" value="email">Unsubscribe</button>
</form>